# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: MintStacks.MintMate
PackageVersion: 2.2.4
PackageLocale: en-US
Publisher: MintStacks
PublisherUrl: https://github.com/mintstacks25
PublisherSupportUrl: https://github.com/mintstacks25/mint/issues
PackageName: MintMate
PackageUrl: https://github.com/mintstacks25/mint
License: Proprietary
Copyright: Copyright © 2026 MintStacks
ShortDescription: MintMate companion console for MintStacks
ReleaseNotesUrl: https://github.com/mintstacks25/mint/releases/tag/v7.5.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/mintstacks25/mint/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
