# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MintStacks.MintMate
PackageVersion: 2.2.4
InstallerType: nullsoft
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/mintstacks25/mint/releases/download/v7.5.1/MintMate-Setup-2.2.4.exe
  InstallerSha256: EECEECF2B1060207050B77622A3EBAE49A01650111207DE998BB80D139B9008A
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-07
